project: "adversarial-training"
dataset: "cifar10"
model_name: "wideresnet_34"
running_name: ""
checkpoint_dir: "./checkpoints/"
logging_dir: "./logs/"
SYS:
    use_cuda: True
    num_gpus: 1
    GPUs: "0"
    num_workers: 8
    random_seed: 41
MODEL:
    num_class: 10
    latent_dim: 640
    input_size: 32
TRAIN:
    data_root: "../data/"
    batch_size: 128
    epochs: 100
    lr: 0.1
    lr_decays: [[75, 0.1], [90, 0.01]]
    weight_decay: 0.0002
    optimizer: "SGD"
    start_epoch: 1
    momentum: 0.9
    save_freq: 5
    start_freq: 10
    RESUME:
        is_resume: False
        start_epoch: 0
        checkpoint_dir: ""
        logging_dir: ""
    TRANSFER:
        is_transfer: False
        start_epoch: 0
        checkpoint_dir: ""
    watchdb: False

ADVER:
    random_init: True
    epsilon: 0.031
    num_steps: 10
    step_size: 0.007
    norm: "l_inf"

TEST:
    epsilon: 0.031
    num_steps: 20
    step_size: 0.003
    batch_size: 128
    random: True

LOSS:
    loss: "trans_swdj"
    TRADES:
        beta: 6
    ALP:
        beta: 0
    Sink:
        eps: 1
        max_iter: 50
    SWD:
        beta: 64
        iter: 32
        adv_type: "pgd"
        use_logit: True
        one_side: False
        weighted: True
    Jac:
        beta: 0.005
        num_proj: 1
        use_logit: True
