project: "adversarial-training"
dataset: "intel"
model_name: "resnet50"
running_name: ""
checkpoint_dir: "./checkpoints/"
logging_dir: "./logs/"
SYS:
  use_cuda: True
  num_gpus: 2
  GPUs: "0, 1"
  num_workers: 8
  random_seed: 41
MODEL:
  num_class: 2
  latent_dim: 640
  input_size: 32
TRAIN:
  data_root: "./../data/intel/seg_train/seg_train/"
  batch_size: 512
  epochs: 50
  lr: 0.001
  weight_decay: 0.0002
  optimizer: "SGD"
  start_epoch: 1
  momentum: 0.9
  save_freq: 5
  start_freq: 10
  RESUME:
    is_resume: False
    start_epoch: 85
    checkpoint_dir: ""
    logging_dir: ""
  TRANSFER:
    is_transfer: False
    start_epoch: 40
    checkpoint_dir: ""
  watchdb: False

ADVER:
  random_init: True
  epsilon: 0.031
  num_steps: 10
  step_size: 0.007
  norm: "l_inf"

TEST:
  data_root: "./../data/intel/seg_test/seg_test/"
  epsilon: 0.031
  num_steps: 20
  step_size: 0.003
  batch_size: 512
  random: True

LOSS:
  loss: "trans_swdj"
  is_embedding: True
  embedding_dim: 256
  TRADES:
    beta: 6
  ALP:
    beta: 0
  Sink:
    eps: 1
    max_iter: 50
  SWD:
    beta: 64
    iter: 32
    adv_type: "pgd"
    use_logit: True
    one_side: False
    weighted: True
  Jac:
    beta: 0.005
    num_proj: 1
    use_logit: True
